doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            'userLogin': App\Doctrine\UserLoginType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
                type: attribute
            FeedBundle:
                is_bundle: true
                type: attribute
                dir: 'Entity'
                prefix: 'FeedBundle\Entity'
                alias: FeedBundle
        metadata_cache_driver:
            type: service
            id: doctrine.cache.memcached
        query_cache_driver:
            type: service
            id: doctrine.cache.memcached
        result_cache_driver:
            type: service
            id: doctrine.cache.memcached

services:
    memcached.doctrine:
        class: Memcached
        factory: Symfony\Component\Cache\Adapter\MemcachedAdapter::createConnection
        arguments:
            - '%env(MEMCACHED_DSN)%'
            - PREFIX_KEY: 'my_app_doctrine'

    doctrine.cache.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - ['setMemcached', ['@memcached.doctrine']]

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
