openapi: 3.0.0
info:
  title: 'My App'
  description: 'This is an awesome app!'
  version: 1.0.0
paths:
  '/api/v2/user/by-login/{user_login}':
    get:
      parameters:
        -
          name: user_login
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
  /api/v1/add-followers:
    post:
      requestBody:
        content:
          application/json:
            schema:
              required:
                - userId
                - followersLogin
                - count
                - async
              properties:
                userId:
                  type: string
                  default: null
                  pattern: \d+
                followersLogin:
                  type: string
                  default: null
                count:
                  type: string
                  default: null
                  pattern: \d+
                async:
                  type: string
                  default: null
                  pattern: 0|1
              type: object
      responses:
        default:
          description: ''
  /api/v4/users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              required:
                - login
                - password
                - roles
                - age
                - isActive
              properties:
                login:
                  type: string
                  default: null
                password:
                  type: string
                  default: null
                roles:
                  type: string
                  default: null
                age:
                  type: string
                  default: null
                  pattern: \d+
                isActive:
                  type: string
                  default: null
                  pattern: true|false
              type: object
      responses:
        default:
          description: ''
  /api/v5/users:
    post:
      responses:
        default:
          description: ''
  /api/v1/get-feed:
    get:
      tags:
        - Лента
      operationId: get_app_api_getfeed_v1_getfeed
      parameters:
        -
          name: userId
          in: query
          description: 'ID пользователя'
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
            pattern: \d+
          example: '135'
        -
          name: count
          in: query
          description: 'ID пользователя'
          required: false
          allowEmptyValue: true
          schema:
            type: string
            default: null
            pattern: \d+
          example: '135'
      responses:
        default:
          description: ''
  /api/v1/tweet:
    get:
      responses:
        default:
          description: ''
    post:
      requestBody:
        content:
          application/json:
            schema:
              required:
                - authorId
                - text
              properties:
                authorId:
                  type: string
                  default: null
                  pattern: \d+
                text:
                  type: string
                  default: null
                async:
                  type: string
                  default: null
                  pattern: 0|1
              type: object
      responses:
        default:
          description: ''
  '/api/v4/users.{format}':
    get:
      parameters:
        -
          name: format
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
  /api/v1/get-users-by-query:
    get:
      parameters:
        -
          name: query
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
        -
          name: perPage
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
            pattern: \d+
        -
          name: page
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
            pattern: \d+
      responses:
        default:
          description: ''
  /api/v1/get-users-by-query-with-aggregation:
    get:
      parameters:
        -
          name: query
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
        -
          name: field
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
      responses:
        default:
          description: ''
  /api/v1/get-users-with-aggregation:
    get:
      parameters:
        -
          name: field
          in: query
          description: ''
          required: false
          allowEmptyValue: false
          schema:
            type: string
            default: null
      responses:
        default:
          description: ''
  /api/v1/token:
    post:
      responses:
        default:
          description: ''
  /api/v1/upload:
    post:
      responses:
        default:
          description: ''
  /api/v1/user:
    get:
      responses:
        default:
          description: ''
    post:
      responses:
        default:
          description: ''
    delete:
      responses:
        default:
          description: ''
    patch:
      responses:
        default:
          description: ''
  /api/v1/user/async:
    post:
      responses:
        default:
          description: ''
  '/api/v1/user/{id}':
    delete:
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
  /api/v1/user/create-user:
    get:
      responses:
        default:
          description: ''
    post:
      responses:
        default:
          description: ''
  '/api/v1/user/update-user/{id}':
    get:
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
    patch:
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''
  /api/v2/user:
    get:
      responses:
        default:
          description: ''
    post:
      responses:
        default:
          description: ''
    patch:
      responses:
        default:
          description: ''
  '/api/v2/user/{user_id}':
    delete:
      parameters:
        -
          name: user_id
          in: path
          required: true
          schema:
            type: string
            pattern: \d+
      responses:
        default:
          description: ''
  /api/v3/user:
    get:
      responses:
        default:
          description: ''
    post:
      responses:
        default:
          description: ''
    delete:
      responses:
        default:
          description: ''
    patch:
      responses:
        default:
          description: ''
  '/api/doc/{area}':
    get:
      parameters:
        -
          name: area
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: ''

